PollsApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    path('latest/', views.LatestDetailView.as_view(), name='latest'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.contrib import admin
from django.db import models
# Create your models here.
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')  # Human readable name

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/All-polls.html'
    # template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/poll_page.html'


class ResultsView(generic.DetailView):
    model = Question
    # template_name = 'polls/results.html'
    template_name = 'polls/results-Modified.html'


class LatestDetailView(generic.ListView):
    context_object_name = 'question_list'
    queryset = Question.objects.order_by('pub_date')
    template_name = 'polls/latest-Polls.html'


def vote(request, question_id):
    # TODO: Complete this question -- partially complete
    question = get_object_or_404(Question, pk=question_id)
    try:  # post['Choice] sent back the Value....
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/poll_page.html', {
            'question': question,
            'error_message': "You forgot to select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/All-polls.html
{% extends "polls/base.html" %}
{% load static %}
        {% block nav %}
            <li class="nav-item"><a class="nav-link active" href="{% url 'polls:index' %}">All Polls</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'polls:latest' %}">Latest Polls</a></li>
            <li class="nav-item"><a class="nav-link" href="/admin">Admin Login</a></li>
        {% endblock nav %}
{% block page %}
    {% if latest_question_list %}
        <ul class="list-group">
            {% for question in latest_question_list %}
            <li class="list-group-item"><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock page %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Poll-App</title>
    <link rel="stylesheet" href="{% static "polls/assets/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="{% static 'polls/assets/css/styles.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-light navbar-expand-lg navigation-clean">
        <div class="container"><a class="navbar-brand" href="#">Polls</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav ms-auto">

                    {% block nav %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:index' %}">All Polls</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:latest' %}">Latest Polls</a></li>
                    <li class="nav-item"><a class="nav-link" href="/admin">Admin Login</a></li>
                    {% endblock nav %}

                </ul>
            </div>
        </div>
    </nav>
{% block page %}
{% endblock page %}
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
<script src="{% static 'polls/assets/js/script.min.js' %}"></script>

</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/latest-Polls.html
{% extends "polls/base.html" %}
{% load static %}
        {% block nav %}
            <li class="nav-item"><a class="nav-link" href="{% url 'polls:index' %}">All Polls</a></li>
            <li class="nav-item"><a class="nav-link active" href="{% url 'polls:latest' %}">Latest Polls</a></li>
            <li class="nav-item"><a class="nav-link" href="/admin">Admin Login</a></li>
        {% endblock nav %}
{% block page %}
    {% if question_list %}
        <ul class="list-group">
            {% for question in question_list %}
            <li class="list-group-item"><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock page %}

polls/templates/polls/poll_page.html
{% extends 'polls/base.html' %}
{% load static %}
{% block page %}
    <div class="card">
        <div class="card-body">
            <div class="container col-form-label">
                <form action="{% url 'polls:vote' question.id %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <h3>{{ question.question_text }}</h3>

                        {% if error_message %}
                            <div class="alert alert-dismissible alert-danger">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                                <strong>Oh snap!</strong> {{ error_message }}
                            </div>
                        {% endif %}

                        {% for choice in question.choice_set.all %}
                            <div class="form-check">
                                <input class="form-check-input" name="choice" type="radio"
                                       id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                <label class="form-check-label"
                                       for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                            </div>
                        {% endfor %}
                    </fieldset>
                    <input class="btn btn-primary" id="Submit-button" type="submit" value="Vote">
                </form>
            </div>
        </div>
    </div>
{% endblock page %}

polls/templates/polls/results-Modified.html
{% extends "polls/base.html" %}
{% load static %}
{% block page %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><span style="text-decoration: underline;">Results</span></h4>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Choice</th>
                            <th>Votes</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for choice in question.choice_set.all %}
                        <tr>
                            <td>{{ choice.choice_text }}</td>
                            <td>{{ choice.votes }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>